### ISSUE TITLE
_cpt issue

### ISSUE THREAD

**Issue by c10b10** [webbushka/atom-react-snippets#14]
If `_cpt` is meant to represent `Class.propTypes = { ... }`, it should instead of:

``` js
.PropTypes = {
  : React.PropTypes.string
}},
```

look like this:

``` js
.propTypes = {
  : React.PropTypes.string
};
```

Shouldn't it?

**Comment by webbushka** [comment]
yes! nice catch, I'll get that updated

**Comment by c10b10** [comment]
What about the trailing curly brace?

**Comment by webbushka** [comment]
crap! sorry I didn't see that... I'm fixing that now
