### ISSUE TITLE
Interferes w/ React atom package

### ISSUE THREAD

**Issue by crobinson42** [webbushka/atom-react-snippets#22]
FYI - I disabled this package because it interferes with React Atom package (https://atom.io/packages/react). I'm unable to use the functionality of React (atom package) when `atom-react-snippets` is enabled.

**Comment by webbushka** [comment]
it shouldn't interfere, it only adds snippets and it adds them under an `_` namespace. Can you give me more information where you are seeing this issue so I can try and reproduce it?

**Comment by crobinson42** [comment]
Hmm.. Not sure now. I just reactivated it and it's working fine. I'll keep an eye on it though and reopen if I am able to pinpoint and reproduce.
