### ISSUE TITLE
Enable/Disable "use strict";

### ISSUE THREAD

**Issue by alexkvazos** [webbushka/atom-react-snippets#23]
Is it possible that we disable the forced use of "use strict";?

Many thanks for this very useful plugin, I still find it useful (despite it bugs me with that use strict thing).

Thanks!

**Comment by webbushka** [comment]
Sure! Would you be willing to create a PR removing them?

**Comment by alexkvazos** [comment]
Can I simply remove them from the snippets?

**Comment by webbushka** [comment]
I don't see why not, no need to have `'use strict;'` anymore, if anyone uses these snippets they are most likely using babel and can use the `babel-plugin-transform-strict-mode` to add strict mode back in after transformation.

**Comment by alexkvazos** [comment]
Waiting on your merge :)
