### ISSUE TITLE
not work with atom emmet

### ISSUE THREAD

**Issue by wargt** [webbushka/atom-react-snippets#25]
_cdm => <_cdm></_cdm>

wtf?

**Comment by bkd705** [comment]
Press enter instead of pressing tab, this is an issue with your auto-complete key settings, not the plugin itself.

**Comment by daraclare** [comment]
Hi there, thanks for the package, but when I type cdm and press return I get:
`componentDidMount: function() {
    
  },`

for ES6, should this not be:

`componentDidMount() {
    
  }`

Maybe i need to make a change in the settings?
