### ISSUE TITLE
wiki out of date

### ISSUE THREAD

**Issue by hozefaj** [webbushka/atom-react-snippets#27]
[wiki page](https://github.com/webbushka/atom-react-snippets/wiki/React-Snippets) for react-snippets looks to be outpf date with with the actual code.

**Comment by webbushka** [comment]
feel free to update it if you see anything wrong... its very possible that it is out of date.

**Comment by hozefaj** [comment]
Let me double check and send a PR if needed

**Comment by hozefaj** [comment]
made necessary updates: https://github.com/webbushka/atom-react-snippets/wiki/React-Snippets
