### ISSUE TITLE
_cer issue

### ISSUE THREAD

**Issue by bluedusk** [webbushka/atom-react-snippets#31]
Hi, the _cer snippet seems not working. when I type cer the menu does not pop up, other snippets work fine.

**Comment by webbushka** [comment]
@bluedusk are you typing `_cer` or `cer`?

**Comment by webbushka** [comment]
@bluedusk I can't reproduce this, `_cer` is working for me, could you take a screen grab of it not working? maybe you have another snippet interfering?

**Comment by DjLeChuck** [comment]
`_cer` is working, I use it every day. :)

I think it was a mistake as you say between `cer` and `_cer`

**Comment by webbushka** [comment]
ok thanks @DjLeChuck, @bluedusk I'm going to close issue. If you find it persists please get in touch.
