### ISSUE TITLE
Adding Class.defaultProps?

### ISSUE THREAD

**Issue by DjLeChuck** [webbushka/atom-react-snippets#33]
Hi,

As we have `React: Class.propTypes = { ... } - _cpt`, why not adding, for example, `React: Class.defaultProps = { ... } - _cdp` for defaultProps?

Currently there is only `React: getDefaultProps() { return {...} } - _gdp` which can not works with `class MyComposent extends React.Component {`

**Comment by webbushka** [comment]
nice find

**Comment by webbushka** [comment]
fixed by #34
