### ISSUE TITLE
Changing _rsc import style

### ISSUE THREAD

**Issue by ahoseinian** [webbushka/atom-react-snippets#36]
Hi,

I was wondering if I can make a pr that changes 
`import React from 'react'`
 to 
`import React, {PropTypes} from 'react'`

as it save writing `React.` before each prop we want to validate

**Comment by webbushka** [comment]
@ahoseinian as opposed to changing `_rsc` what are your thoughts on making a new one `_rscp` that has `{ PropTypes }`?

**Comment by ahoseinian** [comment]
@webbushka I suppose that would be even better so we can keep both styles.

**Comment by webbushka** [comment]
@ahoseinian yeah, I'm totally cool with a PR of that

**Comment by ahoseinian** [comment]
@webbushka Hello, I have submitted a PR a while back, was wondering if you have seen it?

**Comment by webbushka** [comment]
cool thanks @ahoseinian, I've merged #37, I'll push a patch shortly

**Comment by DjLeChuck** [comment]
Nice addition. :)

For the import I have already add the `import React, { PropTypes } from 'react';` https://github.com/webbushka/atom-react-snippets/blob/master/snippets/React%20(JSX).cson#L10-L12

**Comment by ahoseinian** [comment]
@webbushka It was my first open source contribution :) just wanted to say thanks, feels good
