### ISSUE TITLE
Stateless function with support for logic/handlers

### ISSUE THREAD

**Issue by pbojinov** [webbushka/atom-react-snippets#38]
I've found myself using a React Stateless component but with support for onClick handlers and have seen a lot of examples circulate around with the same syntax as well. Here's [an example](https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc#.l0xjt6hq6).

Thoughts on adding support for something like this? And what do you think about naming?

The biggest difference between this and `_rsc` (Related #12) is it's wrapped in a return block with support for functions or logic above the return statement.

```jsx
import React from 'react';

const Cat = ({name}) => {
    const handleClick = () => {
        console.log(`meow from ${name}`);
    };
    return (
        <div onClick={handleClick}>{name}</div>
    );
}

Cat.propTypes = {
    name: React.PropTypes.string
};

export default Cat;
```

**Comment by webbushka** [comment]
cool with me, what about `_rscc` "react stateless component click"?

**Comment by pbojinov** [comment]
Awesome, I'll send a PR with that.
