### ISSUE TITLE
Why are _rsc and _rscp identical?

### ISSUE THREAD

**Issue by derwaldgeist** [webbushka/atom-react-snippets#47]
I was looking for a snippet that would give me just a quick skeleton for a stateless React component. As I mainly use these for composition, they don't have PropTypes. So I was happy to see that there's a `_rsc` and `_rscp` to differentiate between stateless components with and without PropTypes.  But unfortunately, both snippets contain the same content, i.e. they both generate a PropType skeleton. Why is this so?

**Comment by webbushka** [comment]
they should be different 😬 , I'll take a look and get them updated
