### ISSUE TITLE
Support for adding semicolon

### ISSUE THREAD

**Issue by alansouzati** [webbushka/atom-react-snippets#5]
Is there a way to add a configuration for your snippets to allow including semicolon, where the default option is not to have it?

If you think it makes sense, I can write a PR for that.

**Comment by webbushka** [comment]
Are there places that I have omitted semicolons? Can you give me an example of what you mean?

**Comment by alansouzati** [comment]
Sorry I think i've installed two snippets (yours and this one https://github.com/orktes/atom-react).

Please ignore this issue. Do you support ES6 snippets?

**Comment by alansouzati** [comment]
I guess you do, just checked in your code. I may submit a PR to enhance the README with the snippets keys. What do you think? Is there any other place where I can check the prefix instead of going inside this file: https://github.com/webbushka/atom-react-snippets/blob/master/snippets/React%20(JSX).cson

**Comment by alansouzati** [comment]
Answering my own question, it is available here: https://github.com/webbushka/atom-react-snippets/wiki/React-Snippets
