### ISSUE TITLE
Snippets not working anymore after editing config file

### ISSUE THREAD

**Issue by bigfatbird** [webbushka/atom-react-snippets#61]
Tried to modify  "atom-react-snippets/snippets/React (JSX).cson" but after adding a snippet the whole package stopped working. Even an uninstall an reinstall did not resolve the issue.

**Comment by webbushka** [comment]
I actually don't use atom anymore 😬 I've migrated to VS Code... but I can't imagine why a clean install wouldn't solve this...

**Comment by bigfatbird** [comment]
I did remove the application support folder and cleaned up the mess I've been dragging around for years. Should not have happened anyway, but difficult to reproduce I think. Closed.
